### ISSUE TITLE
Create a Matrix room for the project and link to it in the README

### ISSUE THREAD

**Issue by aaronraimist** [DanilaFe/Scylla#2]

**Comment by DanilaFe** [comment]
07efa8764ad38a426ce3c0102a97a22b08d0355a adds the Matrix room address (#scylla:riot.danilafe.com) for a new room created for this project.

**Comment by aaronraimist** [comment]
It appears to be invite only

**Comment by DanilaFe** [comment]
Should be fixed now, sorry!
