### ISSUE TITLE
Add instructions on how to build

### ISSUE THREAD

**Issue by aaronraimist** [DanilaFe/Scylla#3]
I've never used Elm before and this looks really cool but I have no idea how to build it. I installed Elm and tried `elm reactor` and `elm make src/Main.elm` but index.html is always just a blank white page.

**Comment by DanilaFe** [comment]
Thanks for your interest! I've added build instructions in 77edc8464f4ab47994baa0f393f1bd29f1c2a0c9. Also, if you'd like to try Scylla out, there's always a live instance at https://scylla.danilafe.com.

**Comment by aaronraimist** [comment]
Thanks! That works perfectly.
