### ISSUE TITLE
Direct Messages are labeled <No Name>

### ISSUE THREAD

**Issue by ghost** [DanilaFe/Scylla#8]
In cases where a room doesn't have a name and there are only two users, is it possible to detect this and set the room name in the client to "\<User\> - Chat" or something?
I would have tried it myself but the syntax for Elm makes my head spin.

**Comment by DanilaFe** [comment]
Hi! Thanks for opening the issue. I'm a bit swarmed with schoolwork right now, but I will work on a fix / patch soon.

**Comment by DanilaFe** [comment]
Phew! I took a much longer hiatus from working on the project than I expected. Uni workloads just keep going up. This should be fixed in 63fcb2299871f0538334de1ea4a13a842876a4d8 !
